on:
  push:
    branches:
      - main
      - canonical-evidence
      - v2300-cli
      - v2400-dev
      - v2500-dev

  pull_request:
    branches:
      - main
      - canonical-evidence
      - v2300-cli
      - v2400-dev
      - v2500-dev

  workflow_dispatch: